name: CI & SonarCloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Nest.js CLI globally
        run: npm install -g @nestjs/cli

      - name: Install dependencies
        run: npm ci

      - name: Build all packages
        run: npm run build

      - name: Install lcov-result-merger
        run: npm install -g lcov-result-merger

      - name: Run tests with coverage
        run: npm run test:ci

      - name: Merge all lcov files
        run: |
          mkdir -p coverage
          find . -type f -name 'lcov.info' > lcov-files.txt
          lcov-result-merger $(cat lcov-files.txt) > coverage/lcov.info

      - name: Upload coverage to SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
